config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :orders do
    member do
      get :add_item
      get :remove_item
    end
    resources :items do
    end
  end
  match '/404', :to => 'errors#not_found', via: [:get, :post]
  match '/422', :to => 'errors#unprocessable_entity', via: [:get, :post]
  match '/500', :to => 'errors#internal_server_error', via: [:get, :post]

  post '/charges' => 'orders#charges', as: :stripe_charges
  get '/payment' => 'orders#payment', as: :stripe_payment
  devise_for :users
  resources :users
  resources :tickets
  root to: 'events#home'

  resources :exhibitors

  resources :events, except: [:index] do
    resources :exhibitors, only: :new
    resources :tickets
  end

  resources :angles
  resources :activities

  namespace :api do
    resources :events, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/angle.rb
class Angle < ApplicationRecord
end

app/controllers/angles_controller.rb
class AnglesController < ApplicationController
  before_action :set_angle, only: [:show, :edit, :update, :destroy]

  # GET /angles
  # GET /angles.json
  def index
    @angles = Angle.all
  end

  # GET /angles/1
  # GET /angles/1.json
  def show
  end

  # GET /angles/new
  def new
    @angle = Angle.new
  end

  # GET /angles/1/edit
  def edit
  end

  # POST /angles
  # POST /angles.json
  def create
    @angle = Angle.new(angle_params)

    respond_to do |format|
      if @angle.save
        format.html { redirect_to @angle, notice: 'Angle was successfully created.' }
        format.json { render :show, status: :created, location: @angle }
      else
        format.html { render :new }
        format.json { render json: @angle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /angles/1
  # PATCH/PUT /angles/1.json
  def update
    respond_to do |format|
      if @angle.update(angle_params)
        format.html { redirect_to @angle, notice: 'Angle was successfully updated.' }
        format.json { render :show, status: :ok, location: @angle }
      else
        format.html { render :edit }
        format.json { render json: @angle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /angles/1
  # DELETE /angles/1.json
  def destroy
    @angle.destroy
    respond_to do |format|
      format.html { redirect_to angles_url, notice: 'Angle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_angle
      @angle = Angle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def angle_params
      params.require(:angle).permit(:name, :pricing, :state)
    end
end

app/helpers/angles_helper.rb
module AnglesHelper
end

app/views/angles/_form.html.erb
<%= form_with(model: angle, local: true) do |form| %>
  <% if angle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(angle.errors.count, "error") %> prohibited this angle from being saved:</h2>

      <ul>
      <% angle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pricing %>
    <%= form.number_field :pricing %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.check_box :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/angles/edit.html.erb
<h1>Editing Angle</h1>

<%= render 'form', angle: @angle %>

<%= link_to 'Show', @angle %> |
<%= link_to 'Back', angles_path %>

app/views/angles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Angles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pricing</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @angles.each do |angle| %>
      <tr>
        <td><%= angle.name %></td>
        <td><%= angle.pricing %></td>
        <td><%= angle.state %></td>
        <td><%= link_to 'Show', angle %></td>
        <td><%= link_to 'Edit', edit_angle_path(angle) %></td>
        <td><%= link_to 'Destroy', angle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Angle', new_angle_path %>

app/views/angles/new.html.erb
<h1>New Angle</h1>

<%= render 'form', angle: @angle %>

<%= link_to 'Back', angles_path %>

app/views/angles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @angle.name %>
</p>

<p>
  <strong>Pricing:</strong>
  <%= @angle.pricing %>
</p>

<p>
  <strong>State:</strong>
  <%= @angle.state %>
</p>

<%= link_to 'Edit', edit_angle_path(@angle) %> |
<%= link_to 'Back', angles_path %>