config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :orders do
    member do
      get :add_item
      get :remove_item
    end
    resources :items do
    end
  end
  match '/404', :to => 'errors#not_found', via: [:get, :post]
  match '/422', :to => 'errors#unprocessable_entity', via: [:get, :post]
  match '/500', :to => 'errors#internal_server_error', via: [:get, :post]

  post '/charges' => 'orders#charges', as: :stripe_charges
  get '/payment' => 'orders#payment', as: :stripe_payment
  devise_for :users
  resources :users
  resources :tickets
  root to: 'events#home'

  resources :exhibitors

  resources :events, except: [:index] do
    resources :exhibitors, only: :new
    resources :tickets
  end

  resources :angles
  resources :activities

  namespace :api do
    resources :events, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exhibitor.rb
class Exhibitor < ApplicationRecord
    belongs_to :event
    # has_many :activities

    has_one_attached :kbis
    has_one_attached :avis
    has_one_attached :artisan_inscription


  has_many :affiliations
  has_many :activities, through: :affiliations
end

app/controllers/exhibitors_controller.rb
class ExhibitorsController < ApplicationController
  before_action :set_exhibitor, only: [:show, :edit, :update, :destroy]
  # layout "eventster", only: [:new]

  # # GET /exhibitors
  # # GET /exhibitors.json
  # def index
  #   @exhibitors = Exhibitor.all
  # end

  # # GET /exhibitors/1
  # # GET /exhibitors/1.json
  # def show
  # end

  # GET /exhibitors/new
  def new
    @event = Event.friendly.find(params[:event_id])
    @exhibitor = Exhibitor.new
  end

  # GET /exhibitors/1/edit
  # def edit

  #   @event = Event.find(@exhibitor.event_id)
  # end

  # POST /exhibitors
  # POST /exhibitors.json
  def create
    @exhibitor = Exhibitor.new(exhibitor_params)

    respond_to do |format|
      if @exhibitor.save
        format.html { redirect_to event_path(@exhibitor.event_id), notice: 'Exhibitor was successfully created.' }
        format.json { render :show, status: :created, location: @exhibitor }
      else
        format.html { render :new }
        format.json { render json: @exhibitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitors/1
  # PATCH/PUT /exhibitors/1.json
  # def update
  #   respond_to do |format|
  #     if @exhibitor.update(exhibitor_params)
  #       format.html { redirect_to @exhibitor, notice: 'Exhibitor was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @exhibitor }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @exhibitor.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /exhibitors/1
  # # DELETE /exhibitors/1.json
  # def destroy
  #   @exhibitor.destroy
  #   respond_to do |format|
  #     format.html { redirect_to exhibitors_url, notice: 'Exhibitor was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibitor
      @exhibitor = Exhibitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibitor_params
      params.require(:exhibitor).permit(:kbis,
                                        :avis,
                                        :artisan_inscription,
                                        :accepted_cgv,
                                        :is_exhibitor,
                                        :is_angle_a,
                                        :is_angle_b,
                                        :is_angle_c,
                                        :is_angle_d,
                                        :social_name,
                                        :address,
                                        :zipcode,
                                        :country_id,
                                        :phone,
                                        :fax,
                                        :web,
                                        :manager_name,
                                        :manager_phone,
                                        :manager_email,
                                        :commercial_name,
                                        :commercial_phone,
                                        :commercial_email,
                                        :marketing_name,
                                        :marketing_phone,
                                        :marketing_email,
                                        :email,
                                        :naf,
                                        :siren,
                                        :siret,
                                        :tva_code,
                                        :company_creation_date,
                                        :is_experienced,
                                        :experience_event,
                                        :experience_year,
                                        :contact_name,
                                        :contact_title,
                                        :contact_phone,
                                        :contact_mobile,
                                        :contact_address_type,
                                        :contact_address,
                                        :contact_email,
                                        :billing_address_type,
                                        :billing_address,
                                        :signage,
                                        :other_activity,
                                        :products,
                                        :brands,
                                        :insurance_agreement,
                                        :insurance_type,
                                        :booth_surface,
                                        :booth_junk_surface,
                                        :majoration_central_allery,
                                        :confort_surface,
                                        :turnkey_surface,
                                        :turnkey_options,
                                        :badges_count,
                                        :invitations_count,
                                        :logo_confirmed,
                                        :home_ad_banner,
                                        :visitor_ad_banner,
                                        :page_ad_banner,
                                        :summit_logo_confirmed,
                                        :bag_confirmed,
                                        :payment_version,
                                        :wishes,
                                        :event_id,
                                        :angle_id, city_ids: [])
    end
end

app/helpers/exhibitors_helper.rb
module ExhibitorsHelper
end

app/views/exhibitors/edit.html.erb
<h1>Editing Exhibitor</h1>

<%= render 'form', exhibitor: @exhibitor %>

<%= link_to 'Show', @exhibitor %> |
<%= link_to 'Back', exhibitors_path %>

app/views/exhibitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exhibitors</h1>

<table>
  <thead>
    <tr>
      <th>Is exhibitor</th>
      <th>Social name</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>Country</th>
      <th>Phone</th>
      <th>Fax</th>
      <th>Web</th>
      <th>Manager name</th>
      <th>Manager phone</th>
      <th>Manager email</th>
      <th>Commercial name</th>
      <th>Commercial phone</th>
      <th>Commercial email</th>
      <th>Marketing name</th>
      <th>Marketing phone</th>
      <th>Marketing email</th>
      <th>Email</th>
      <th>Naf</th>
      <th>Siren</th>
      <th>Tva code</th>
      <th>Company creation date</th>
      <th>Is experienced</th>
      <th>Experience event</th>
      <th>Experience year</th>
      <th>Contact name</th>
      <th>Contact title</th>
      <th>Contact phone</th>
      <th>Contact mobile</th>
      <th>Contact address type</th>
      <th>Contact address</th>
      <th>Contact email</th>
      <th>Billing address type</th>
      <th>Billing address</th>
      <th>Signage</th>
      <th>Other activity</th>
      <th>Products</th>
      <th>Brands</th>
      <th>Insurance agreement</th>
      <th>Insurance type</th>
      <th>Booth surface</th>
      <th>Booth junk surface</th>
      <th>Majoration central allery</th>
      <th>Confort surface</th>
      <th>Turnkey surface</th>
      <th>Turnkey options</th>
      <th>Badges count</th>
      <th>Invitations count</th>
      <th>Logo confirmed</th>
      <th>Home ad banner</th>
      <th>Visitor ad banner</th>
      <th>Page ad banner</th>
      <th>Summit logo confirmed</th>
      <th>Bag confirmed</th>
      <th>Payment version</th>
      <th>Wishes</th>
      <th>Event</th>
      <th>Angle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exhibitors.each do |exhibitor| %>
      <tr>
        <td><%= exhibitor.is_exhibitor %></td>
        <td><%= exhibitor.social_name %></td>
        <td><%= exhibitor.address %></td>
        <td><%= exhibitor.zipcode %></td>
        <td><%= exhibitor.country_id %></td>
        <td><%= exhibitor.phone %></td>
        <td><%= exhibitor.fax %></td>
        <td><%= exhibitor.web %></td>
        <td><%= exhibitor.manager_name %></td>
        <td><%= exhibitor.manager_phone %></td>
        <td><%= exhibitor.manager_email %></td>
        <td><%= exhibitor.commercial_name %></td>
        <td><%= exhibitor.commercial_phone %></td>
        <td><%= exhibitor.commercial_email %></td>
        <td><%= exhibitor.marketing_name %></td>
        <td><%= exhibitor.marketing_phone %></td>
        <td><%= exhibitor.marketing_email %></td>
        <td><%= exhibitor.email %></td>
        <td><%= exhibitor.naf %></td>
        <td><%= exhibitor.siren %></td>
        <td><%= exhibitor.tva_code %></td>
        <td><%= exhibitor.company_creation_date %></td>
        <td><%= exhibitor.is_experienced %></td>
        <td><%= exhibitor.experience_event %></td>
        <td><%= exhibitor.experience_year %></td>
        <td><%= exhibitor.contact_name %></td>
        <td><%= exhibitor.contact_title %></td>
        <td><%= exhibitor.contact_phone %></td>
        <td><%= exhibitor.contact_mobile %></td>
        <td><%= exhibitor.contact_address_type %></td>
        <td><%= exhibitor.contact_address %></td>
        <td><%= exhibitor.contact_email %></td>
        <td><%= exhibitor.billing_address_type %></td>
        <td><%= exhibitor.billing_address %></td>
        <td><%= exhibitor.signage %></td>
        <td><%= exhibitor.other_activity %></td>
        <td><%= exhibitor.products %></td>
        <td><%= exhibitor.brands %></td>
        <td><%= exhibitor.insurance_agreement %></td>
        <td><%= exhibitor.insurance_type %></td>
        <td><%= exhibitor.booth_surface %></td>
        <td><%= exhibitor.booth_junk_surface %></td>
        <td><%= exhibitor.majoration_central_allery %></td>
        <td><%= exhibitor.confort_surface %></td>
        <td><%= exhibitor.turnkey_surface %></td>
        <td><%= exhibitor.turnkey_options %></td>
        <td><%= exhibitor.badges_count %></td>
        <td><%= exhibitor.invitations_count %></td>
        <td><%= exhibitor.logo_confirmed %></td>
        <td><%= exhibitor.home_ad_banner %></td>
        <td><%= exhibitor.visitor_ad_banner %></td>
        <td><%= exhibitor.page_ad_banner %></td>
        <td><%= exhibitor.summit_logo_confirmed %></td>
        <td><%= exhibitor.bag_confirmed %></td>
        <td><%= exhibitor.payment_version %></td>
        <td><%= exhibitor.wishes %></td>
        <td><%= exhibitor.event_id %></td>
        <td><%= exhibitor.angle_id %></td>
        <td><%= link_to 'Show', exhibitor %></td>
        <td><%= link_to 'Edit', edit_exhibitor_path(exhibitor) %></td>
        <td><%= link_to 'Destroy', exhibitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exhibitor', new_exhibitor_path %>

app/views/exhibitors/new.html.erb
<div class="container-fluid" id="colored-subheader" style="background-image: url('<%= @event.event_cover %>'); background-size: cover;">
</div>

<div class="container event-data text-center">
  <div class="event-logo">
    <% if @event.logo.attached? %>
      <%= image_tag @event.logo %>
    <% else %>
      <%= image_tag('default-cover.png') %>
    <% end %>
  </div>
  <div class="event-body">
    <br>
    <div class="event-title">
      <h1><%= @event.name %></h1>
    </div>
    <div class="event-date">
      <%= l @event.start_date, format: :long %> - <%= l @event.end_date, format: :long %>
    </div>
  </div>
</div>


<div class="container form-container">
  <%= render 'form', exhibitor: @exhibitor %>
</div>

app/views/exhibitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is exhibitor:</strong>
  <%= @exhibitor.is_exhibitor %>
</p>

<p>
  <strong>Social name:</strong>
  <%= @exhibitor.social_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @exhibitor.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @exhibitor.zipcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @exhibitor.country %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @exhibitor.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @exhibitor.fax %>
</p>

<p>
  <strong>Web:</strong>
  <%= @exhibitor.web %>
</p>

<p>
  <strong>Manager name:</strong>
  <%= @exhibitor.manager_name %>
</p>

<p>
  <strong>Manager phone:</strong>
  <%= @exhibitor.manager_phone %>
</p>

<p>
  <strong>Manager email:</strong>
  <%= @exhibitor.manager_email %>
</p>

<p>
  <strong>Commercial name:</strong>
  <%= @exhibitor.commercial_name %>
</p>

<p>
  <strong>Commercial phone:</strong>
  <%= @exhibitor.commercial_phone %>
</p>

<p>
  <strong>Commercial email:</strong>
  <%= @exhibitor.commercial_email %>
</p>

<p>
  <strong>Marketing name:</strong>
  <%= @exhibitor.marketing_name %>
</p>

<p>
  <strong>Marketing phone:</strong>
  <%= @exhibitor.marketing_phone %>
</p>

<p>
  <strong>Marketing email:</strong>
  <%= @exhibitor.marketing_email %>
</p>

<p>
  <strong>Email:</strong>
  <%= @exhibitor.email %>
</p>

<p>
  <strong>Naf:</strong>
  <%= @exhibitor.naf %>
</p>

<p>
  <strong>Siren:</strong>
  <%= @exhibitor.siren %>
</p>

<p>
  <strong>Tva code:</strong>
  <%= @exhibitor.tva_code %>
</p>

<p>
  <strong>Company creation date:</strong>
  <%= @exhibitor.company_creation_date %>
</p>

<p>
  <strong>Is experienced:</strong>
  <%= @exhibitor.is_experienced %>
</p>

<p>
  <strong>Experience event:</strong>
  <%= @exhibitor.experience_event %>
</p>

<p>
  <strong>Experience year:</strong>
  <%= @exhibitor.experience_year %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @exhibitor.contact_name %>
</p>

<p>
  <strong>Contact title:</strong>
  <%= @exhibitor.contact_title %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @exhibitor.contact_phone %>
</p>

<p>
  <strong>Contact mobile:</strong>
  <%= @exhibitor.contact_mobile %>
</p>

<p>
  <strong>Contact address type:</strong>
  <%= @exhibitor.contact_address_type %>
</p>

<p>
  <strong>Contact address:</strong>
  <%= @exhibitor.contact_address %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @exhibitor.contact_email %>
</p>

<p>
  <strong>Billing address type:</strong>
  <%= @exhibitor.billing_address_type %>
</p>

<p>
  <strong>Billing address:</strong>
  <%= @exhibitor.billing_address %>
</p>

<p>
  <strong>Signage:</strong>
  <%= @exhibitor.signage %>
</p>

<p>
  <strong>Other activity:</strong>
  <%= @exhibitor.other_activity %>
</p>

<p>
  <strong>Products:</strong>
  <%= @exhibitor.products %>
</p>

<p>
  <strong>Brands:</strong>
  <%= @exhibitor.brands %>
</p>

<p>
  <strong>Insurance agreement:</strong>
  <%= @exhibitor.insurance_agreement %>
</p>

<p>
  <strong>Insurance type:</strong>
  <%= @exhibitor.insurance_type %>
</p>

<p>
  <strong>Booth surface:</strong>
  <%= @exhibitor.booth_surface %>
</p>

<p>
  <strong>Booth junk surface:</strong>
  <%= @exhibitor.booth_junk_surface %>
</p>

<p>
  <strong>Majoration central allery:</strong>
  <%= @exhibitor.majoration_central_allery %>
</p>

<p>
  <strong>Confort surface:</strong>
  <%= @exhibitor.confort_surface %>
</p>

<p>
  <strong>Turnkey surface:</strong>
  <%= @exhibitor.turnkey_surface %>
</p>

<p>
  <strong>Turnkey options:</strong>
  <%= @exhibitor.turnkey_options %>
</p>

<p>
  <strong>Badges count:</strong>
  <%= @exhibitor.badges_count %>
</p>

<p>
  <strong>Invitations count:</strong>
  <%= @exhibitor.invitations_count %>
</p>

<p>
  <strong>Logo confirmed:</strong>
  <%= @exhibitor.logo_confirmed %>
</p>

<p>
  <strong>Home ad banner:</strong>
  <%= @exhibitor.home_ad_banner %>
</p>

<p>
  <strong>Visitor ad banner:</strong>
  <%= @exhibitor.visitor_ad_banner %>
</p>

<p>
  <strong>Page ad banner:</strong>
  <%= @exhibitor.page_ad_banner %>
</p>

<p>
  <strong>Summit logo confirmed:</strong>
  <%= @exhibitor.summit_logo_confirmed %>
</p>

<p>
  <strong>Bag confirmed:</strong>
  <%= @exhibitor.bag_confirmed %>
</p>

<p>
  <strong>Payment version:</strong>
  <%= @exhibitor.payment_version %>
</p>

<p>
  <strong>Wishes:</strong>
  <%= @exhibitor.wishes %>
</p>

<p>
  <strong>Event:</strong>
  <%= @exhibitor.event_id %>
</p>

<p>
  <strong>Angle:</strong>
  <%= @exhibitor.is_angle_a %> a
  <%= @exhibitor.is_angle_b %> b
  <%= @exhibitor.is_angle_c %> c
  <%= @exhibitor.is_angle_d %> d
</p>

<%= link_to 'Edit', edit_exhibitor_path(@exhibitor) %> |
<%= link_to 'Back', exhibitors_path %>