config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :orders do
    member do
      get :add_item
      get :remove_item
    end
    resources :items do
    end
  end
  match '/404', :to => 'errors#not_found', via: [:get, :post]
  match '/422', :to => 'errors#unprocessable_entity', via: [:get, :post]
  match '/500', :to => 'errors#internal_server_error', via: [:get, :post]

  post '/charges' => 'orders#charges', as: :stripe_charges
  get '/payment' => 'orders#payment', as: :stripe_payment
  devise_for :users
  resources :users
  resources :tickets
  root to: 'events#home'

  resources :exhibitors

  resources :events, except: [:index] do
    resources :exhibitors, only: :new
    resources :tickets
  end

  resources :angles
  resources :activities

  namespace :api do
    resources :events, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :order
    belongs_to :event
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_order

  before_action :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @items = @order.items
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to order_items_path(@order), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_order
      @order = Order.find(params[:order_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:first_name, :last_name, :email, :order_id, :event_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="modal-lgLabel">Ticket : <%= item.id %></h5>
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
</div>
<div class="modal-body">
  <%= form_for [@order, item], :method => :PUT, remote: true do |form| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>


    <div class="actions">
      <%= form.submit 'Assigner', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/edit.js.erb
$("#modal-lg .modal-content").html("<%= escape_javascript(render 'form', item: @item, order: @order) %>");
$("#modal-lg").modal('show');

app/views/items/index.html.erb
<div class="container items-list-container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>
  <h1>Commande N°<%= @order.id %> pour "<%= @order.event.name %>"</h1>

  <table class="table order-items-list">
    <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>

      <th>Event</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.first_name %></td>
        <td><%= item.last_name %></td>
        <td><%= item.email %></td>

        <td><%= item.event.name %></td>

        <td>
          <% unless item.email.present? %>
            <%= link_to '<i class="fas fa-user-plus"></i>'.html_safe, edit_order_item_path(@order, item), remote: true %>
          <% end %>
        </td>

      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

</div>

<div class="modal fade" id="modal-lg" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>


<script type="text/javascript" charset="utf-8">
    $('.modal').on('hidden.bs.modal', function () {
        $(this).find('form')[0].reset();
    });
</script>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @item.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @item.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @item.email %>
</p>

<p>
  <strong>Order:</strong>
  <%= @item.order_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @item.event_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>